apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: demo-voting-app

spec:
  ports:
    - targetPort: 6379
      port: 6379

      #we need to link the service to the one of the 5 pods for that we use selector and use diff filter ex: labels

  selector:
    name: redis-pod
    app: demo-voting-app